#define MARANHAO
#define ADD_FSOBC
#define ADD_M2OBC
#define ANA_BSFLUX
#define ANA_BTFLUX
#define ANA_NUDGCOEF
#define ASSUMED_SHAPE
#define ATM_PRESS
#define AVERAGES
#define BULK_FLUXES
#define CURVGRID
#define DEFLATE
#define DJ_GRADPS
#define DOUBLE_PRECISION
#define EMINUSP
#define GLS_MIXING
#define HDF5
#define KANTHA_CLAYSON
#define MASKING
#define MIX_ISO_TS
#define MIX_GEO_UV
#define MPI
#define NONLINEAR
#define NONLIN_EOS
#define N2S2_HORAVG
#define PERFECT_RESTART
#define POWER_LAW
#define PROFILE
#define QCORRECTION
#define K_GSCHEME
#define RADIATION_2D
#define  RAMP_TIDES
#define REDUCE_ALLGATHER
#define SALINITY
#define SOLAR_SOURCE
#define SOLVE3D
#define SSH_TIDES
#define TS_DIF4
#define UV_ADV
#define UV_COR
#define UV_U3HADVECTION
#define UV_C4VADVECTION
#define UV_QDRAG
#define UV_TIDES
#define UV_VIS2
#define VAR_RHO_2D
